Repository GT4SD/gt4sd-core, pull requests merged in 2022-10, with the labels that each got.

#145 TDC Oracle integration
  examples/regression_transformer/README.md
  requirements.txt
  setup.cfg
  src/gt4sd/properties/core.py
  src/gt4sd/properties/molecules/__init__.py
  src/gt4sd/properties/molecules/core.py
  src/gt4sd/properties/utils.py
  src/gt4sd/training_pipelines/tests/test_training_regression_transformer.py
Labels: enhancement, cla-signed

#148 fix: change default to true
  requirements.txt
  src/gt4sd/cli/trainer.py
Labels: cla-signed

#149 update: pytorch_lightning and gpu training
  requirements.txt
  setup.cfg
  src/gt4sd/cli/trainer.py
  src/gt4sd/configuration.py
  src/gt4sd/frameworks/gflownet/arg_parser/parser.py
  src/gt4sd/frameworks/gflownet/tests/test_gfn.py
  src/gt4sd/frameworks/gflownet/train/core.py
  src/gt4sd/frameworks/granular/train/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/gflownet/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
  src/gt4sd/training_pipelines/tests/test_training_gflownet.py
Labels: cla-signed

#151 Wheel issue and pkg_resource refactor
  requirements.txt
  setup.cfg
  src/gt4sd/conftest.py
  src/gt4sd/tests/utils.py
  src/gt4sd/training_pipelines/__init__.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/lm_datasets.py
  src/gt4sd/training_pipelines/tests/test_training_diffusion.py
  src/gt4sd/training_pipelines/tests/test_training_gflownet.py
  src/gt4sd/training_pipelines/tests/test_training_guacamol_baselines_smiles_lstm.py
  src/gt4sd/training_pipelines/tests/test_training_language_modeling.py
  src/gt4sd/training_pipelines/tests/test_training_moses_organ.py
  src/gt4sd/training_pipelines/tests/test_training_moses_vae.py
  src/gt4sd/training_pipelines/tests/test_training_paccmann_vae.py
  src/gt4sd/training_pipelines/tests/test_training_regression_transformer.py
  src/gt4sd/training_pipelines/tests/test_training_torchdrug_gcpn.py
  src/gt4sd/training_pipelines/tests/test_training_torchdrug_graphaf.py
  src/gt4sd/training_pipelines/torchdrug/unpatch.py
Labels: cla-signed

#152 Python 3.8 compatibility
  README.md
  conda.yml
  conda_gpu.yml
  requirements.txt
  setup.cfg
  src/gt4sd/algorithms/controlled_sampling/advanced_manufacturing/implementation/core.py
  src/gt4sd/frameworks/gflownet/dataloader/data_module.py
  src/gt4sd/training_pipelines/__init__.py
  src/gt4sd/training_pipelines/tests/test_training_moses_organ.py
  src/gt4sd/training_pipelines/tests/test_training_moses_vae.py
  vcs_requirements.txt
Labels: cla-signed

#154 feat: updating gt4sd base image.
  Dockerfile
Labels: cla-signed

#157 Tolerance values RegressionTransformer
  examples/regression_transformer/README.md
  src/gt4sd/algorithms/conditional_generation/regression_transformer/core.py
  src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py
  src/gt4sd/algorithms/conditional_generation/tests/test_regression_transformer.py
  src/gt4sd/algorithms/generation/diffusion/implementation.py
  src/gt4sd/training_pipelines/diffusion/core.py
  src/gt4sd/training_pipelines/torchdrug/graphaf/core.py
Labels: bug, enhancement, cla-signed

#158 feat: Initial molgx integration
  README.md
  extras_requirements.txt
  notebooks/gt4sd_molgx_example.ipynb
  requirements.txt
  setup.cfg
  src/gt4sd/algorithms/__init__.py
  src/gt4sd/algorithms/conditional_generation/molgx/__init__.py
  src/gt4sd/algorithms/conditional_generation/molgx/core.py
  src/gt4sd/algorithms/conditional_generation/molgx/implementation.py
  src/gt4sd/algorithms/conditional_generation/tests/test_molgx.py
  src/gt4sd/algorithms/generation/molgx/core.py
  src/gt4sd/algorithms/generation/molgx/implementation.py
  src/gt4sd/extras/__init__.py
Labels: cla-signed
