Repository GT4SD/gt4sd-core, pull requests merged in 2022-02, with the labels that each got.

#23 Running tests action on PRs
  .github/workflows/tests.yaml
Labels: ci, cla-signed

#24 chore: updating .clabot message and list
  .clabot
  .github/workflows/cla-signature.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  iCLA.md
Labels: cla-signed

#33 Black release version
  CONTRIBUTING.md
  dev_requirements.txt
  src/gt4sd/algorithms/controlled_sampling/class_controlled_sampling/core.py
  src/gt4sd/algorithms/controlled_sampling/class_controlled_sampling/implementation.py
  src/gt4sd/algorithms/controlled_sampling/paccmann_gp/implementation.py
  src/gt4sd/algorithms/generation/molgx/core.py
  src/gt4sd/algorithms/generation/molgx/implementation.py
  src/gt4sd/domains/materials/scorer.py
  src/gt4sd/frameworks/granular/ml/models/module.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/lm_datasets.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/models.py
Labels: cla-signed

#35 feat: adding notebooks.
  notebooks/README.md
  notebooks/explore-molecular-generative-models-latent-spaces.ipynb
  notebooks/requirements.txt
  src/gt4sd/algorithms/controlled_sampling/advanced_manufacturing/implementation/nccr/core.py
  src/gt4sd/algorithms/controlled_sampling/class_controlled_sampling/core.py
  src/gt4sd/algorithms/controlled_sampling/class_controlled_sampling/implementation.py
  src/gt4sd/algorithms/controlled_sampling/paccmann_gp/implementation.py
  src/gt4sd/algorithms/generation/molgx/core.py
  src/gt4sd/algorithms/generation/molgx/implementation.py
  src/gt4sd/domains/materials/scorer.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/lm_datasets.py
Labels: documentation, enhancement

#44 GT4SD inference client
  .github/workflows/tests.yaml
  README.md
  setup.cfg
  src/gt4sd/cli/inference.py
  src/gt4sd/cli/trainer.py
Labels: cla-signed

#46 Add PGT algorithm
  src/gt4sd/algorithms/generation/pgt/__init__.py
  src/gt4sd/algorithms/generation/pgt/core.py
  src/gt4sd/algorithms/generation/pgt/implementation.py
  src/gt4sd/algorithms/generation/tests/test_pgt.py
Labels: cla-signed

#47 Add notebook for PGT algorithm
  notebooks/explore-pgt.ipynb
Labels: cla-signed
