Repository GT4SD/gt4sd-core, pull requests merged in 2022-05, with the labels that each got.

#65 Demo
  notebooks/discovery-demo.ipynb
  notebooks/regression-transformer-demo.ipynb
  notebooks/requirements.txt
  src/gt4sd/algorithms/conditional_generation/regression_transformer/core.py
  src/gt4sd/algorithms/conditional_generation/reinvent/core.py
  src/gt4sd/algorithms/conditional_generation/reinvent/implementation.py
  src/gt4sd/algorithms/conditional_generation/tests/test_regression_transformer.py
  src/gt4sd/algorithms/generation/torchdrug/implementation.py
Labels: documentation, cla-signed

#66 feat: ensuring sentencepiece before pytorch_lightning.
  src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
  src/gt4sd/training_pipelines/tests/test_training_language_modeling.py
Labels: cla-signed

#67 granular trainer: search for the models in the given config by default
  src/gt4sd/cli/trainer.py
  src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
Labels: cla-signed

#69 Demo fix
  notebooks/discovery-demo.ipynb
Labels: bug, cla-signed

#70 Improving demos
  dev_requirements.txt
  notebooks/discovery-demo.ipynb
  notebooks/explore-molecular-generative-models-latent-spaces.ipynb
  notebooks/isgc2022-demo.ipynb
  notebooks/regression-transformer-demo.ipynb
  requirements.txt
  setup.cfg
  src/gt4sd/cli/pl_to_hf_converter.py
Labels: cla-signed

#59 feat: setting up binder hosting.
  Dockerfile
  README.md
Labels: cla-signed

#73 missing package_data in sdist, add wheel
  .github/workflows/pypi.yaml
  setup.cfg
  src/gt4sd/__init__.py
Labels: cla-signed

#75 chore: fix bdist_wheel build by installing wheel.
  .github/workflows/pypi.yaml
Labels: cla-signed

#76 Ci setup
  .github/workflows/pypi.yaml
  setup.cfg
  src/gt4sd/__init__.py
Labels: cla-signed

#77 Multiproperty support in Regression Transformers
  src/gt4sd/algorithms/conditional_generation/regression_transformer/core.py
  src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py
  src/gt4sd/algorithms/conditional_generation/tests/test_regression_transformer.py
  src/gt4sd/algorithms/core.py
Labels: enhancement, cla-signed

#78 Reinvent seq length
  src/gt4sd/algorithms/conditional_generation/reinvent/core.py
  src/gt4sd/algorithms/conditional_generation/reinvent/implementation.py
Labels: enhancement, cla-signed

#79 fix: upper bound for protobuf to fix tensorflow compatibility errors in CI.
  requirements.txt
  src/gt4sd/__init__.py
Labels: cla-signed
