Repository GT4SD/gt4sd-core, pull requests merged in 2022-03, with the labels that each got.

#48 implementing model saving.
  .github/workflows/tests.yaml
  .gitignore
  README.md
  requirements.txt
  setup.cfg
  src/gt4sd/algorithms/controlled_sampling/advanced_manufacturing/core.py
  src/gt4sd/algorithms/controlled_sampling/advanced_manufacturing/implementation/nccr/core.py
  src/gt4sd/algorithms/controlled_sampling/paccmann_gp/core.py
  src/gt4sd/algorithms/core.py
  src/gt4sd/algorithms/generation/polymer_blocks/core.py
  src/gt4sd/algorithms/generation/polymer_blocks/implementation.py
  src/gt4sd/cli/algorithms.py
  src/gt4sd/cli/inference.py
  src/gt4sd/cli/saving.py
  src/gt4sd/cli/trainer.py
  src/gt4sd/domains/materials/__init__.py
  src/gt4sd/frameworks/granular/tokenizer/tokenizer.py
  src/gt4sd/training_pipelines/__init__.py
  src/gt4sd/training_pipelines/paccmann/core.py
  src/gt4sd/training_pipelines/paccmann/vae/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
  src/gt4sd/training_pipelines/tests/test_training_paccmann_vae.py
Labels: cla-signed

#50 Enable LM saving
  src/gt4sd/algorithms/__init__.py
  src/gt4sd/algorithms/core.py
  src/gt4sd/algorithms/generation/pgt/core.py
  src/gt4sd/algorithms/generation/pgt/implementation.py
  src/gt4sd/cli/pl_to_hf_converter.py
  src/gt4sd/frameworks/granular/dataloader/dataset.py
  src/gt4sd/training_pipelines/__init__.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/models.py
Labels: cla-signed

#49 Torchdrug integration
  conda.yml
  pyproject.toml
  requirements.txt
  setup.cfg
  src/gt4sd/algorithms/__init__.py
  src/gt4sd/algorithms/generation/tests/test_torchdrug.py
  src/gt4sd/algorithms/generation/torchdrug/__init__.py
  src/gt4sd/algorithms/generation/torchdrug/checks.py
  src/gt4sd/algorithms/generation/torchdrug/core.py
  src/gt4sd/algorithms/generation/torchdrug/implementation.py
  src/gt4sd/frameworks/granular/arg_parser/parser.py
  src/gt4sd/frameworks/granular/dataloader/data_module.py
  src/gt4sd/frameworks/granular/ml/module.py
  src/gt4sd/frameworks/granular/train/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/core.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/lm_datasets.py
  src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/models.py
Labels: cla-signed

#53 doc: Demo about RegressionTransformer
  dev_requirements.txt
  notebooks/regression-transformer-demo.ipynb
Labels: documentation, cla-signed

#54 doc: pin jinja2 version to fix doc deployment
  dev_requirements.txt
Labels: documentation, ci, cla-signed

#51 feat: moses and guacamol baselines training pipelines
  README.md
  setup.cfg
  src/gt4sd/algorithms/__init__.py
  src/gt4sd/algorithms/conditional_generation/guacamol/core.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/__init__.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/graph_ga.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/graph_mcts.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/moses_aae.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/moses_organ.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/moses_vae.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/smiles_ga.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/smiles_lstm_hc.py
  src/gt4sd/algorithms/conditional_generation/guacamol/implementation/smiles_lstm_ppo.py
  src/gt4sd/algorithms/conditional_generation/tests/test_guacamol.py
  src/gt4sd/algorithms/prediction/paccmann/core.py
  src/gt4sd/cli/algorithms.py
  src/gt4sd/cli/load_arguments_from_dataclass.py
  src/gt4sd/configuration.py
  src/gt4sd/domains/materials/scorer.py
  src/gt4sd/frameworks/torch/__init__.py
  src/gt4sd/training_pipelines/__init__.py
  src/gt4sd/training_pipelines/guacamol_baselines/__init__.py
  src/gt4sd/training_pipelines/guacamol_baselines/core.py
  src/gt4sd/training_pipelines/guacamol_baselines/smiles_lstm/__init__.py
  src/gt4sd/training_pipelines/guacamol_baselines/smiles_lstm/core.py
  src/gt4sd/training_pipelines/moses/__init__.py
  src/gt4sd/training_pipelines/moses/core.py
  src/gt4sd/training_pipelines/moses/organ/__init__.py
  src/gt4sd/training_pipelines/moses/organ/core.py
  src/gt4sd/training_pipelines/moses/vae/__init__.py
  src/gt4sd/training_pipelines/moses/vae/core.py
  src/gt4sd/training_pipelines/tests/molecules.smiles
  src/gt4sd/training_pipelines/tests/test_training_guacamol_baselines_smiles_lstm.py
  src/gt4sd/training_pipelines/tests/test_training_moses_organ.py
  src/gt4sd/training_pipelines/tests/test_training_moses_vae.py
  src/gt4sd/training_pipelines/tests/test_training_paccmann_vae.py
  vcs_requirements.txt
Labels: cla-signed
