Repository GT4SD/gt4sd-core, pull requests merged in 2022-12, with the labels that each got.

#170 RT training - option to save dataset
  src/gt4sd/properties/tests/test_properties.py
  src/gt4sd/training_pipelines/regression_transformer/core.py
  src/gt4sd/training_pipelines/regression_transformer/implementation.py
  src/gt4sd/training_pipelines/regression_transformer/utils.py
Labels: enhancement, cla-signed

#172 implementing a finetuning feature
  src/gt4sd/training_pipelines/paccmann/core.py
  src/gt4sd/training_pipelines/paccmann/vae/core.py
Labels: enhancement, cla-signed

#174 Update Keybert's version in requirements
  requirements.txt
Labels: cla-signed

#175 Paccmann vae inference
  examples/molecular_vae/README.md
  setup.cfg
  src/gt4sd/algorithms/conditional_generation/paccmann_rl/implementation.py
Labels: cla-signed

#178 Moses upgrade
  notebooks/discovery-demo.ipynb
  requirements.txt
  src/gt4sd/algorithms/conditional_generation/guacamol/core.py
  src/gt4sd/training_pipelines/moses/vae/core.py
  src/gt4sd/training_pipelines/tests/test_training_moses_vae.py
  vcs_requirements.txt
Labels: bug, cla-signed
