Repository GT4SD/gt4sd-core, pull requests merged in 2023-01, with the labels that each got.

#179 RT saving pipeline
  examples/regression_transformer/README.md
  examples/regression_transformer/inference_generate.json
  examples/regression_transformer/inference_predict.json
  examples/regression_transformer/rt_config.json
  src/gt4sd/algorithms/conditional_generation/regression_transformer/core.py
  src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py
  src/gt4sd/algorithms/conditional_generation/regression_transformer/utils.py
  src/gt4sd/training_pipelines/regression_transformer/core.py
  src/gt4sd/training_pipelines/regression_transformer/implementation.py
  src/gt4sd/training_pipelines/regression_transformer/utils.py
  src/gt4sd/training_pipelines/terminator_training.json
  vcs_requirements.txt
Labels: enhancement, cla-signed

#185 fix: granular deprecated pl.Trainer flag
  src/gt4sd/frameworks/granular/train/core.py
Labels: cla-signed

#188 Updating pymatgen installation/deps
  README.md
  docs/_static/gt4sd_case_study.jpg
  docs/_static/gt4sd_case_study.png
  requirements.txt
  setup.cfg
Labels: cla-signed

#189 Proper CGCNN model loading
  src/gt4sd/properties/__init__.py
  src/gt4sd/properties/crystals/core.py
  src/gt4sd/properties/tests/test_properties.py
Labels: cla-signed

#187 CGCNN Refactoring
  setup.cfg
  src/gt4sd/frameworks/cgcnn/data.py
  src/gt4sd/properties/crystals/core.py
  src/gt4sd/properties/tests/1000041.cif
  src/gt4sd/properties/tests/test_properties.py
  src/gt4sd/training_pipelines/cgcnn/core.py
  src/gt4sd/training_pipelines/tests/cgcnn-sample/1000041.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/1000050.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/1101051.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/1507756.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/7206075.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/9000046.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/9009743.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/9011050.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/9011998.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/9012304.cif
  src/gt4sd/training_pipelines/tests/cgcnn-sample/atom_init.json
  src/gt4sd/training_pipelines/tests/cgcnn-sample/id_prop.csv
  src/gt4sd/training_pipelines/tests/test_training_cgnn.py
Labels: enhancement, invalid, cla-signed

#190 test: enable cgcnn test
  notebooks/cgcnn-sample/atom_init.json
  src/gt4sd/properties/tests/test_properties.py
Labels: invalid, cla-signed

#191 Add RandomForest classifier for crystals
  src/gt4sd/frameworks/crystals_rfc/__init__.py
  src/gt4sd/frameworks/crystals_rfc/atomic_data.csv
  src/gt4sd/frameworks/crystals_rfc/feature_engine.py
  src/gt4sd/frameworks/crystals_rfc/rf_classifier.py
  src/gt4sd/properties/crystals/__init__.py
  src/gt4sd/properties/crystals/core.py
  src/gt4sd/properties/tests/crf_data.csv
  src/gt4sd/properties/tests/test_properties.py
  src/gt4sd/training_pipelines/__init__.py
  src/gt4sd/training_pipelines/cgcnn/core.py
  src/gt4sd/training_pipelines/crystals_crf/__init__.py
  src/gt4sd/training_pipelines/crystals_crf/core.py
  src/gt4sd/training_pipelines/tests/crystals_rfc_sample.csv
  src/gt4sd/training_pipelines/tests/test_training_crystals_rfc.py
Labels: cla-signed
